name: school_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.1
  bloc: ^7.2.1
  dio: ^4.0.3
  firebase_core: ^1.0.2
  firebase_auth: ^3.1.1
  intl:
  percent_indicator:
  cloud_firestore: ^3.0.0
  popover:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/